# Read the documentation: https://symfony.com/doc/master/bundles/FOSRestBundle/index.html
fos_rest:
  routing_loader:
    default_format: json
    include_format: false
  body_listener: true
  body_converter:
    enabled: true
    validate: true
    validation_errors_argument: validationErrors # This is the default value
  format_listener:
    rules:
      - { path: ^/api, prefer_extension: true, fallback_format: json, priorities: [json] }
  zone:
    - { path: ^/api/* }
  exception:
    enabled: true
  param_fetcher_listener: true
  view:
    view_response_listener: 'force'
    formats:
      json: true
  serializer:
    serialize_null: true